### ISSUE TITLE
[Feature Request]: Incompatible file handling

### ISSUE THREAD

**Issue by U-C-S** [Vignesh-Vin/jpeg-resaver#3]
- Let the user know if the said file is not compatible to be converted to a `.jpg` through a alert box. 
- Like for example, take a random file with some extension and rename it to .jpeg and use this tool on it. No output nor Error.

**Comment by vignesh-seven** [comment]
Sure, will do (soon).

**Comment by vignesh-seven** [comment]
Feature is added in v0.5.3

**Comment by vignesh-seven** [comment]
Now it will show a error message on the "drag n drop area" if the file is not compatible, and also shows a "Processing" message while it is converting images.

Thanks for the idea 💡
